### ISSUE TITLE
run_ok

### ISSUE THREAD

**Issue by filipegmedeiros** [swelljoe/spinner#1]
U can make available the fuction run_ok? :+1:

**Comment by swelljoe** [comment]
It's here: https://github.com/swelljoe/run_ok

And, it's part of the Virtualmin shell library slib which is here (and has a bunch of other shell utility/UI functions you might find useful if you're making the kinds of shell scripts I'm making): https://github.com/virtualmin/slib

**Comment by swelljoe** [comment]
Oh, actually, I just noticed the unicode check is still in run_ok. That fails too often on shells that *do* support Unicode (most do now) to be reasonable and can probably be removed. I think it's been removed from the version in slib.
